Mvc/MvcTravelTrip/Models/Classes/Blog.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MvcTravelTrip.Models.Classes
{
    public class Blog
    {
        [Key]
        public int BlogID { get; set; }
        public string BlogHeading { get; set; }
        public DateTime BlogDate { get; set; }
        public string Description { get; set; }
        public string BlogImage { get; set; }
        public ICollection<Comment> Comments { get; set; }
    }
}

Mvc/MvcTravelTrip/Controllers/BlogController.cs
using MvcTravelTrip.Models.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcTravelTrip.Controllers
{
    public class BlogController : Controller
    {
        // GET: Blog Controller
        Context c = new Context();
        BlogComment bc = new BlogComment();
        // GET: Blog
        public ActionResult Index()
        {
            //var values = c.Blogs.ToList();
            bc.Value1 = c.Blogs.ToList();
            //bc.Value3 = c.Blogs.Take(2).ToList();
            bc.Value3 = c.Blogs.OrderByDescending(x => x.BlogID).Take(3).ToList();
            bc.Value4 = c.Comments.OrderByDescending(x => x.CommentID).Take(3).ToList();
            return View(bc);
        }

        public ActionResult BlogDetail(int id)
        {
            //var findBlog = c.Blogs.Where(x => x.BlogID == id).ToList();
            bc.Value1 = c.Blogs.Where(x => x.BlogID == id).ToList();
            bc.Value2 = c.Comments.Where(x => x.Blogid == id).ToList();
            return View(bc);
        }

        [HttpGet]
        public PartialViewResult LeaveAComment(int id)
        {
            ViewBag.value = id;
            return PartialView();
        }
        [HttpPost]
        public PartialViewResult LeaveAComment(Comment com)
        {
            c.Comments.Add(com);
            c.SaveChanges();
            return PartialView();
        }
    }
}

Mvc/MvcTravelTrip/Views/Blog/BlogDetail.cshtml
@model MvcTravelTrip.Models.Classes.BlogComment
@{
    ViewBag.Title = "BlogDetail";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <title>Personal Blog a Blogging Category Flat Bootstarp  Responsive Website Template | Single :: w3layouts</title>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>
    <!----//webfonts---->
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <!--end slider -->
    <!--script-->

</head>
<body>
    <!---header---->
    <div class="header">
    </div>
    <!--/header-->
    <div class="single">
        <div class="container">
            <div class="col-md-12 single-main">
                <div class="single-grid">
                    @foreach (var item in Model.Value1)
                    {
                        <img src="@item.BlogImage" alt="" style="margin-bottom:20px" height=400 />
                        <h2>@item.BlogHeading</h2>
                        <p>
                            @item.Description
                        </p>
                    }
                </div>

                @foreach (var item in Model.Value2)
                {
                    <ul class="comment-list">
                        <li>
                            <img src="~/web2/images/avatar.png" class="img-responsive" alt="">
                            <div class="desc">
                                <p><strong>@item.UserName:</strong> @item.CommentName</p>
                            </div>
                            <div class="clearfix"></div>
                        </li>
                    </ul>
                }

                @Html.Action("LeaveAComment", "Blog")
            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>

Mvc/MvcTravelTrip/Views/Blog/Index.cshtml
@model MvcTravelTrip.Models.Classes.BlogComment
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_TestLayout.cshtml";
}

<!--
Author: W3layouts
Author URL: http://w3layouts.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE HTML>
<html>
<head>
    <link href="~/web2/css/bootstrap.css" rel='stylesheet' type='text/css' />
    <link href="~/web2/css/style.css" rel='stylesheet' type='text/css' />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="keywords" content="Personal Blog Responsive web template, Bootstrap Web Templates, Flat Web Templates, Andriod Compatible web template,
	Smartphone Compatible web template, free webdesigns for Nokia, Samsung, LG, SonyErricsson, Motorola web design" />
    <script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
    <!----webfonts---->
    <link href='http://fonts.googleapis.com/css?family=Oswald:100,400,300,700' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Lato:100,300,400,700,900,300italic' rel='stylesheet' type='text/css'>

</head>
<body>
    <!---header---->
    <div class="header">
        <div class="container">

            <div class="clearfix"></div>

        </div>
    </div>
    <!--/header-->
    <div class="single">
        <div class="container">
            <div class="col-md-8 single-main">
                @foreach (var item in Model.Value1)
                {
                    <div class="single-grid">
                        <img src="@item.BlogImage" alt="" style="margin-bottom:20px" height=400 />
                        @item.BlogHeading
                        <p>
                            @item.Description.Substring(0, 100)...
                        </p>
                        <a href="/Blog/BlogDetail/@item.BlogID" class="btn btn-primary">Read More</a>
                    </div>
                    <br /><br />
                }

            </div>

            <div class="col-md-4 side-content">
                <div class="recent">
                    <h3>Latest Blogs</h3>
                    @foreach (var item in Model.Value3)
                    {
                        <ul>
                            <li><a href="/Blog/BlogDetail/@item.BlogID/">@item.BlogHeading</a></li>
                        </ul>
                    }

                </div>
                <div class="comments">
                    <h3>last Comments</h3>
                    @foreach (var item in Model.Value4)
                    {
                        <ul>
                            <li><a href="/Blog/BlogDetail/@item.Blogid/"><b>@item.UserName: </b> @item.CommentName</a></li>
                        </ul>
                    }
                </div>

            </div>
            <div class="clearfix"></div>
        </div>
    </div>
</body>
</html>

<script>
    if (window.history.replaceState) {
        window.history.replaceState(null, null, window.location.href);
    }
</script>

Mvc/MvcTravelTrip/Views/Blog/LeaveAComment.cshtml
<div class="content-form">
    <h3>Leave a comment</h3>
    <form method="post">
        <input type="hidden" placeholder="ID" name="Blogid" value="@ViewBag.value" required readonly />
        <input type="text" placeholder="User Name" name="UserName" required />
        <input type="text" placeholder="E-mail Address" name="Mail" required />
        <textarea placeholder="Comment" name="CommentName" required></textarea>
        <input type="submit" value="Send" />
    </form>
</div>

<script>
    if ( window.history.replaceState ) {
        window.history.replaceState( null, null, window.location.href );
    }
</script>